routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes([
    'register' => false, // Registration Routes...
    'reset' => false, // Password Reset Routes...
    'verify' => false, // Email Verification Routes...
]);

Route::get('/home', [App\Http\Controllers\Admin\HomeController::class, 'index'])->name('home');

Route::group([
    'as' => 'admin.',
    'prefix' => 'admin/',
    'middleware' => [
        'auth',
        \App\Http\Middleware\CheckIsAdmin::class,
    ],
], function () {
    Route::resource('products', \App\Http\Controllers\Admin\ProductController::class, [
        'except' => [ 'show' ]
    ]);

    Route::resource('clients', \App\Http\Controllers\Admin\ClientController::class, [
        'except' => [ 'show' ]
    ]);
    Route::get('orders',[\App\Http\Controllers\Admin\OrderController::class,'index'])->name('orders');
});

app/Models/Client.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;
use Spatie\MediaLibrary\MediaCollections\Models\Media;

class Client extends Model implements HasMedia
{
    use HasFactory, InteractsWithMedia;

    protected $fillable = ['user_id', 'full_name', 'phone_number','admin_created_at','admin_updated_at'];

    public function user(){
        return $this->belongsTo(User::class);
    }

    public function orders(){
        return $this->hasMany(Order::class);
    }

    public function registerMediaCollections(): void
    {
        $this->addMediaCollection('avatars')
            ->useFallbackUrl('/img/avatar.jpeg')
            ->useFallbackPath(public_path('/img/avatar.jpeg'));
    }


    public function registerMediaConversions(Media $media = null): void
    {
        $this->addMediaConversion('small')
            ->crop('crop-center',300,300)
            ->format('jpg')
            ->quality(80)
            ->sharpen(10)
            ->performOnCollections('avatars');
    }
}

app/Http/Controllers/Admin/ClientController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Client;
use App\Models\User;
use Illuminate\Http\Request;
use Yajra\DataTables\Facades\DataTables;

class ClientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            return Datatables::of(Client::with('user'))
                ->editColumn('created_at', function ($data) {
                    return $data->created_at->format('d.m.Y h:m:s');
                })
                ->editColumn('updated_at', function ($data) {
                    return $data->updated_at->format('d.m.Y h:m:s');
                })
                ->addColumn('photo', function ($data) {
                    $img = '<img width="150px" src="' . asset($data->getFirstMediaUrl('avatars', 'small')) . '" />';
                    return $img;
                })
                ->addColumn('action', function ($data) {
                    $btns = '<a class="btn btn-sm btn-primary" href="' . route('admin.clients.edit', $data->id) . '">Редактировать</a>';
                    $btns .= '<button class="btn btn-sm btn-danger" onclick="Delete(' . $data->id . ')" >Удалить</button>';
                    return $btns;
                })
                ->rawColumns(['action', 'photo'])
                ->make(true);;
        }
        return view('admin.client.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.client.create');
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'full_name' => 'required|string|min:2|max:256',
            'email' => 'required|email|unique:users,email',
            'password' => 'required|confirmed|min:6|max:30',
            'photo' => 'nullable|mimes:jpg,png|max:5120|dimensions:min_width=300,min_height=300',
            'phone' => ['required', 'regex:/^(\+\d{1,2}\s?)?1?\-?\.?\s?\(?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4}$/', 'unique:clients,phone_number', 'min:10', 'max:20']
        ]);
        $user = new User();
        $user->name = $request->input('full_name');
        $user->email = $request->input('email');
        $user->password = bcrypt($request->input('password'));
        $user->save();
        $user->assignRole('client');
        $client = new Client();
        $client->full_name = $request->input('full_name');
        $client->phone_number = $request->input('phone');
        $client->user_id = $user->id;
        $client->save();
        $client->addMedia($request->file('photo'))->toMediaCollection('avatars');
        return redirect(route('admin.clients.index'))->with(['success' => 'Данные добавлены']);
        //
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('admin.client.edit')->with(['client' => Client::with('user')->findOrFail($id)]);
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user_id = Client::findOrFail($id)->user_id;
        $this->validate($request, [
            'full_name' => 'required|string|min:2|max:256',
            'email' => 'required|email|unique:users,email,' . $user_id,
            'password' => 'nullable|confirmed|min:6|max:30',
            'photo' => 'nullable|mimes:jpg,png|max:5120|dimensions:min_width=300,min_height=300',
            'phone' => ['required', 'regex:/^(\+\d{1,2}\s?)?1?\-?\.?\s?\(?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4}$/', 'unique:clients,phone_number,' . $id]
        ]);
        $user = User::findOrFail($user_id);
        $user->name = $request->input('full_name');
        $user->email = $request->input('email');
        if ($request->has('password')) {
            $user->password = bcrypt($request->input('password'));
        }
        $user->save();
        $client = Client::find($id);
        $client->full_name = $request->input('full_name');
        $client->phone_number = $request->input('phone');
        $client->save();
        if ($request->has('photo')) {
            $client->clearMediaCollection('avatars');
            $client->addMedia($request->file('photo'))->toMediaCollection('avatars');
        }
        return redirect(route('admin.clients.index'))->with(['success' => 'Данные обновлены']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $client = Client::findOrFail($id);
        $client->clearMediaCollection('avatars');
        return Response()->json($client->delete());
    }
}

resources/views/admin/client/create.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')
    <h1 class="m-0 text-dark">Clients-Add new client</h1>
@stop

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <form action="{{ route('admin.clients.store')  }}" method="POST" enctype="multipart/form-data">

                        <div class="form-body col-md-12">
                            @csrf
                            <div class="form-group col-md-6 float-md-left">
                                <label class="control-label">
                                    ФИО
                                    <span class="required" aria-required="true"> * </span>
                                </label>
                                <input type="text"
                                       class="form-control  {{ $errors->has('full_name')?' is-invalid':'' }}"
                                       name="full_name" id="full_name" required min="2" max="256"
                                       value="{{old('full_name')}}">
                                @if($errors->has('full_name'))
                                    <div class='col-sm-12'><small class='text-danger'>
                                            @foreach($errors->get('full_name') as $message)
                                            {{ $message }}</br>
                                            @endforeach
                                        </small></div>
                                @endif
                            </div>
                            <div class="form-group col-md-6 float-md-right">
                                <label class="control-label">
                                    Э-почта
                                    <span class="required" aria-required="true"> * </span>
                                </label>
                                <input type="email" class="form-control  {{ $errors->has('email')?' is-invalid':'' }}"
                                       name="email" id="email" required min="4" max="256" value="{{old('email')}}">
                                @if($errors->has('email'))
                                    <div class='col-sm-12'><small class='text-danger'>
                                            @foreach($errors->get('email') as $message)
                                            {{ $message }}</br>
                                            @endforeach
                                        </small></div>
                                @endif
                            </div>

                            <div class="form-group col-md-6 float-md-left">
                                <label class="control-label">
                                    Телефон
                                    <span class="required" aria-required="true"> * </span>
                                </label>
                                <input type="text" class="form-control  {{ $errors->has('phone')?' is-invalid':'' }}"
                                       name="phone" id="phone" required min="10" max="20" value="{{old('phone')}}">
                                @if($errors->has('phone'))
                                    <div class='col-sm-12'><small class='text-danger'>
                                            @foreach($errors->get('phone') as $message)
                                            {{ $message }}</br>
                                            @endforeach
                                        </small></div>
                                @endif
                            </div>
                            <div class="form-group col-md-6 float-md-right">
                                <label class="control-label">
                                    Фотография
                                    <span class="required" aria-required="true"> * </span>
                                </label>
                                <input type="file" class="form-control  {{ $errors->has('photo')?' is-invalid':'' }}"
                                       name="photo" id="photo">
                                @if($errors->has('photo'))
                                    <div class='col-sm-12'><small class='text-danger'>
                                            @foreach($errors->get('photo') as $message)
                                            {{ $message }}</br>
                                            @endforeach
                                        </small></div>
                                @endif
                            </div>

                            <div class="form-group col-md-6 float-md-left">
                                <label class="control-label">
                                    Пароль
                                    <span class="required" aria-required="true"> * </span>
                                </label>
                                <input type="password"
                                       class="form-control  {{ $errors->has('password')?' is-invalid':'' }}"
                                       name="password" id="password" required min="6" max="30">
                                @if($errors->has('password'))
                                    <div class='col-sm-12'><small class='text-danger'>
                                            @foreach($errors->get('password') as $message)
                                            {{ $message }}</br>
                                            @endforeach
                                        </small></div>
                                @endif
                            </div>
                            <div class="form-group col-md-6 float-md-right">
                                <label class="control-label">
                                    Потвердить пароль
                                    <span class="required" aria-required="true"> * </span>
                                </label>
                                <input type="password" class="form-control"
                                       name="password_confirmation" id="password_confirmation" required min="6"
                                       max="30">
                            </div>
                        </div>
                        <div class="row col-md-12">
                            <div class="col-md-12 text-center">
                                <button type="submit" class="btn btn-circle btn-primary">
                                    Сохранить
                                </button>
                                <a class="btn btn-circle btn-danger" href="{{ route('admin.clients.index') }}">
                                    Отмена
                                </a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@stop
@section('js')
    <script>
    </script>
@stop

resources/views/admin/client/edit.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')
    <h1 class="m-0 text-dark">Clients-Edit</h1>
@stop

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <form action="{{ route('admin.clients.update',$client->id)  }}" method="POST"
                          enctype="multipart/form-data">

                        <div class="form-body col-md-12">
                            @csrf
                            @method('put')
                            <div class="form-group col-md-6">
                                <label class="control-label">
                                    ФИО
                                    <span class="required" aria-required="true"> * </span>
                                </label>
                                <input type="text"
                                       class="form-control  {{ $errors->has('full_name')?' is-invalid':'' }}"
                                       name="full_name" id="full_name" required min="2" max="256"
                                       value="{{$client->full_name}}">
                                @if($errors->has('full_name'))
                                    <div class='col-sm-12'><small class='text-danger'>
                                            @foreach($errors->get('full_name') as $message)
                                            {{ $message }}</br>
                                            @endforeach
                                        </small></div>
                                @endif
                            </div>
                            <div class="form-group col-md-6">
                                <label class="control-label">
                                    Э-почта
                                    <span class="required" aria-required="true"> * </span>
                                </label>
                                <input type="email" class="form-control  {{ $errors->has('email')?' is-invalid':'' }}"
                                       name="email" id="email" required min="4" max="256"
                                       value="{{$client->user->email}}">
                                @if($errors->has('email'))
                                    <div class='col-sm-12'><small class='text-danger'>
                                            @foreach($errors->get('email') as $message)
                                            {{ $message }}</br>
                                            @endforeach
                                        </small></div>
                                @endif
                            </div>

                            <div class="form-group col-md-6">
                                <label class="control-label">
                                    Телефон
                                    <span class="required" aria-required="true"> * </span>
                                </label>
                                <input type="text" class="form-control  {{ $errors->has('phone')?' is-invalid':'' }}"
                                       name="phone" id="phone" required min="10" max="20"
                                       value="{{$client->phone_number}}">
                                @if($errors->has('phone'))
                                    <div class='col-sm-12'><small class='text-danger'>
                                            @foreach($errors->get('phone') as $message)
                                            {{ $message }}</br>
                                            @endforeach
                                        </small></div>
                                @endif
                            </div>
                            <div class="form-group col-md-6">
                                <label class="control-label">
                                    Фотография
                                </label>
                                <img width="300px" src="{{asset($client->getFirstMediaUrl('avatars'))}}"/>
                                <input type="file" class="form-control  {{ $errors->has('photo')?' is-invalid':'' }}"
                                       name="photo" id="photo">
                                @if($errors->has('photo'))
                                    <div class='col-sm-12'><small class='text-danger'>
                                            @foreach($errors->get('photo') as $message)
                                            {{ $message }}</br>
                                            @endforeach
                                        </small></div>
                                @endif
                            </div>

                            <div class="form-group col-md-6">
                                <label class="control-label">
                                    Пароль
                                </label>
                                <input type="password"
                                       class="form-control  {{ $errors->has('password')?' is-invalid':'' }}"
                                       name="password" id="password" min="6" max="30">
                                @if($errors->has('password'))
                                    <div class='col-sm-12'><small class='text-danger'>
                                            @foreach($errors->get('password') as $message)
                                            {{ $message }}</br>
                                            @endforeach
                                        </small></div>
                                @endif
                            </div>
                            <div class="form-group col-md-6">
                                <label class="control-label">
                                    Потвердить пароль
                                </label>
                                <input type="password" class="form-control"
                                       name="password_confirmation" id="password_confirmation" min="6"
                                       max="30">
                            </div>
                        </div>
                        <div class="row col-md-12">
                            <div class="col-md-12 text-center">
                                <button type="submit" class="btn btn-circle btn-primary">
                                    Сохранить
                                </button>
                                <a class="btn btn-circle btn-danger" href="{{ route('admin.clients.index') }}">
                                    Отмена
                                </a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@stop
@section('js')
    <script>
    </script>
@stop

resources/views/admin/client/index.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')
@section('css')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/7.2.0/sweetalert2.min.css">
@stop

@section('content_header')
    <h1 class="m-0 text-dark">Clients</h1>
@stop

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    @if (session('success'))
                        <div class="col-xs-12" style="padding-top: 20px;">
                            <div class="alert alert-success alert-dismissible">
                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                                <i class="icon fa fa-check"></i>
                                {{ session('success') }}
                            </div>
                        </div>
                @endif
                <!-- BEGIN Portlet PORTLET-->
                    <div class="portlet light" data-error-display="notific8">
                        <div class="portlet-title">
                            <div class="caption font-primary">
                            </div>
                            <div class="col-lg-9">
                                <a class="btn btn-sm btn-success" href="{{route('admin.clients.create')}}">
                                    <i class="fa fa-plus"></i>Добавить
                                </a>
                            </div>
                        </div>

                        <div class="table-responsive">
                            <table class="table table-striped table-hover table-bordered" id="dataTable">
                                <thead>
                                <tr>
                                    <th>
                                        id
                                    </th>
                                    <th>
                                        ФИО
                                    </th>
                                    <th>
                                        Э-почта
                                    </th>
                                    <th>
                                        Номер телефона
                                    </th>
                                    <th>
                                        Аватар
                                    </th>
                                    <th>
                                        Дата создание
                                    </th>
                                    <th>
                                        Дата обновление
                                    </th>
                                    <th>
                                        Действие
                                    </th>
                                </tr>
                                </thead>

                            </table>
                        </div>

                    </div>
                    <!-- END PORTLET-->
                </div>
            </div>
        </div>
    </div>
@stop
@section('js')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/7.2.0/sweetalert2.all.min.js"></script>
    <script src="{{ asset('vendor/datatables/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('vendor/datatables/js/dataTables.bootstrap4.min.js') }}"></script>
    <script>
        $('#dataTable').DataTable({
            processing: true,
            serverSide: true,
            ajax: window.location.href,
            columns: [
                {data: 'id', name: 'id'},
                {data: 'full_name', name: 'full_name'},
                {data: 'user.email', name: 'email'},
                {data: 'phone_number', name: 'phone_number'},
                {data: 'photo', name: 'photo'},
                {data: 'created_at', name: 'created_at'},
                {data: 'updated_at', name: 'updated_at'},
                {data: 'action', name: 'action'}
            ]
        });

        function Delete(id) {
            swal({
                title: "Вы точно хотите удалить?",
                text: "Выбранные вами данные будут удалены",
                type: "warning",
                buttons: true,
                dangerMode: true,
            }).then((willDelete) => {
                if (willDelete) {
                    $.ajax({
                        type: 'DELETE',
                        dataType: 'json',
                        url: window.location.href + '/' + id,
                        data: ({"_token": $('meta[name="csrf-token"]').attr('content')})
                    }).done(function (success) {
                        if (success) {
                            $('#dataTable').DataTable().ajax.reload();
                            swal({
                                title: "Успешно удален!",
                                type: "success",
                            });
                        }
                    })

                }
            });
        }
    </script>
@stop