routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes([
    'register' => false, // Registration Routes...
    'reset' => false, // Password Reset Routes...
    'verify' => false, // Email Verification Routes...
]);

Route::get('/home', [App\Http\Controllers\Admin\HomeController::class, 'index'])->name('home');

Route::group([
    'as' => 'admin.',
    'prefix' => 'admin/',
    'middleware' => [
        'auth',
        \App\Http\Middleware\CheckIsAdmin::class,
    ],
], function () {
    Route::resource('products', \App\Http\Controllers\Admin\ProductController::class, [
        'except' => [ 'show' ]
    ]);

    Route::resource('clients', \App\Http\Controllers\Admin\ClientController::class, [
        'except' => [ 'show' ]
    ]);
    Route::get('orders',[\App\Http\Controllers\Admin\OrderController::class,'index'])->name('orders');
});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;
use Spatie\MediaLibrary\MediaCollections\Models\Media;

class Product extends Model  implements HasMedia
{
    use HasFactory,InteractsWithMedia;

    protected $fillable = [ 'name', 'SKU','price','admin_created_at','admin_updated_at'];

    public function orders(){
        return $this->hasMany(Order::class);
    }

    public function registerMediaCollections(): void
    {
        $this->addMediaCollection('photo')
            ->useFallbackUrl('/img/63f2afb6927676e79a0c9d48a69f52a2.png')
            ->useFallbackPath(public_path('/img/63f2afb6927676e79a0c9d48a69f52a2.png'));
    }

    public function registerMediaConversions(Media $media = null): void
    {
        $this->addMediaConversion('small')
            ->crop('crop-center',300,300)
            ->format('jpg')
            ->quality(80)
            ->sharpen(10)
            ->performOnCollections('photo');
    }
}

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Product;
use Illuminate\Http\Request;
use Yajra\DataTables\Facades\DataTables;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {

        if ($request->ajax()) {
            return Datatables::of(Product::all())
                ->editColumn('created_at', function ($data) {
                    return $data->created_at->format('d.m.Y h:m:s');
                })
                ->editColumn('updated_at', function ($data) {
                    return $data->updated_at->format('d.m.Y h:m:s');
                })
                ->addColumn('photo', function ($data) {
                    $img = '<img width="150px" src="' . asset($data->getFirstMediaUrl('photo', 'small')) . '" />';
                    return $img;
                })
                ->addColumn('action', function ($data) {
                    $btns = '<a class="btn btn-sm btn-primary" href="' . route('admin.products.edit', $data->id) . '">Редактировать</a>';
                    $btns .= '<button class="btn btn-sm btn-danger" onclick="Delete(' . $data->id . ')" >Удалить</button>';
                    return $btns;
                })
                ->rawColumns(['action', 'photo'])
                ->make(true);;
        }
        return view('admin.product.index');
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.product.create');
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|string|min:2|max:256',
            'sku' => 'required|string|min:2|max:256|unique:products,sku',
            'price' => 'required|numeric|min:0.01',
            'photo' => 'nullable|mimes:jpg,png|max:5120|dimensions:min_width=300,min_height=300'
        ]);
        $product = new Product();
        $product->name = $request->input('name');
        $product->sku = $request->input('sku');
        $product->price = $request->input('price');
        $product->save();
        $product->addMedia($request->file('photo'))->toMediaCollection('photo');
        return redirect(route('admin.products.index'))->with(['success' => 'Данные добавлены']);
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('admin.product.edit')->with(['product' => Product::findOrFail($id)]);
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required|string|min:2|max:256',
            'sku' => 'required|string|min:2|max:256|unique:products,sku,' . $id,
            'price' => 'required|numeric|min:0.01',
            'photo' => 'nullable|mimes:jpg,png|max:5120|dimensions:min_width=300,min_height=300'
        ]);
        $product = Product::findOrFail($id);
        $product->name = $request->input('name');
        $product->sku = $request->input('sku');
        $product->price = $request->input('price');
        $product->save();
        if ($request->has('photo')) {
            $product->clearMediaCollection('photo');
            $product->addMedia($request->file('photo'))->toMediaCollection('photo');
        }
        return redirect(route('admin.products.index'))->with(['success' => 'Данные добавлены']);
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $product = Product::findOrFail($id);
        $product->clearMediaCollection('photo');
        return Response()->json($product->delete());
    }
}

resources/views/admin/product/create.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')
    <h1 class="m-0 text-dark">Product-Create</h1>
@stop

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <form action="{{ route('admin.products.store')  }}" method="POST" enctype="multipart/form-data">

                        <div class="form-body col-md-12">
                            @csrf
                            <div class="form-group col-md-6">
                                <label class="control-label">
                                    Наименование
                                    <span class="required" aria-required="true"> * </span>
                                </label>
                                <input type="text"
                                       class="form-control  {{ $errors->has('name')?' is-invalid':'' }}"
                                       name="name" id="name" required min="2" max="256"
                                       value="{{old('name')}}">
                                @if($errors->has('name'))
                                    <div class='col-sm-12'><small class='text-danger'>
                                            @foreach($errors->get('name') as $message)
                                            {{ $message }}</br>
                                            @endforeach
                                        </small></div>
                                @endif
                            </div>
                            <div class="form-group col-md-6">
                                <label class="control-label">
                                    SKU
                                    <span class="required" aria-required="true"> * </span>
                                </label>
                                <input type="text" class="form-control  {{ $errors->has('sku')?' is-invalid':'' }}"
                                       name="sku" id="sku" required min="4" max="256" value="{{old('sku')}}">
                                @if($errors->has('sku'))
                                    <div class='col-sm-12'><small class='text-danger'>
                                            @foreach($errors->get('sku') as $message)
                                            {{ $message }}</br>
                                            @endforeach
                                        </small></div>
                                @endif
                            </div>

                            <div class="form-group col-md-6">
                                <label class="control-label">
                                    Цена
                                    <span class="required" aria-required="true"> * </span>
                                </label>
                                <input type="number" class="form-control  {{ $errors->has('price')?' is-invalid':'' }}"
                                       name="price" id="price" required min="0.01" value="{{old('price')}}" step="0.01">
                                @if($errors->has('price'))
                                    <div class='col-sm-12'><small class='text-danger'>
                                            @foreach($errors->get('price') as $message)
                                            {{ $message }}</br>
                                            @endforeach
                                        </small></div>
                                @endif
                            </div>
                            <div class="form-group col-md-6">
                                <label class="control-label">
                                    Фотография
                                    <span class="required" aria-required="true"> * </span>
                                </label>
                                <input type="file" class="form-control  {{ $errors->has('photo')?' is-invalid':'' }}"
                                       name="photo" id="photo" value="{{old('photo')}}">
                                @if($errors->has('photo'))
                                    <div class='col-sm-12'><small class='text-danger'>
                                            @foreach($errors->get('photo') as $message)
                                            {{ $message }}</br>
                                            @endforeach
                                        </small></div>
                                @endif
                            </div>
                        </div>
                        <div class="row col-md-12">
                            <div class="col-md-12 text-center">
                                <button type="submit" class="btn btn-circle btn-primary">
                                    Сохранить
                                </button>
                                <a class="btn btn-circle btn-danger" href="{{ route('admin.products.index') }}">
                                    Отмена
                                </a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/admin/product/edit.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')
    <h1 class="m-0 text-dark">Product-Edit</h1>
@stop

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <form action="{{ route('admin.products.update',$product->id)  }}" method="POST"
                          enctype="multipart/form-data">

                        <div class="form-body col-md-12">
                            @csrf
                            @method('put')
                            <div class="form-group col-md-6">
                                <label class="control-label">
                                    Наименование
                                    <span class="required" aria-required="true"> * </span>
                                </label>
                                <input type="text"
                                       class="form-control  {{ $errors->has('name')?' is-invalid':'' }}"
                                       name="name" id="name" required min="2" max="256"
                                       value="{{$product->name}}">
                                @if($errors->has('name'))
                                    <div class='col-sm-12'><small class='text-danger'>
                                            @foreach($errors->get('name') as $message)
                                            {{ $message }}</br>
                                            @endforeach
                                        </small></div>
                                @endif
                            </div>
                            <div class="form-group col-md-6">
                                <label class="control-label">
                                    SKU
                                    <span class="required" aria-required="true"> * </span>
                                </label>
                                <input type="text" class="form-control  {{ $errors->has('sku')?' is-invalid':'' }}"
                                       name="sku" id="sku" required min="4" max="256" value="{{$product->sku}}">
                                @if($errors->has('sku'))
                                    <div class='col-sm-12'><small class='text-danger'>
                                            @foreach($errors->get('sku') as $message)
                                            {{ $message }}</br>
                                            @endforeach
                                        </small></div>
                                @endif
                            </div>

                            <div class="form-group col-md-6">
                                <label class="control-label">
                                    Цена
                                    <span class="required" aria-required="true"> * </span>
                                </label>
                                <input type="number" class="form-control  {{ $errors->has('price')?' is-invalid':'' }}"
                                       name="price" id="price" required min="0.01" value="{{$product->price}}"
                                       step="0.01">
                                @if($errors->has('price'))
                                    <div class='col-sm-12'><small class='text-danger'>
                                            @foreach($errors->get('price') as $message)
                                            {{ $message }}</br>
                                            @endforeach
                                        </small></div>
                                @endif
                            </div>
                            <div class="form-group col-md-6">
                                <label class="control-label">
                                    Фотография
                                </label>
                                <img width="300px" src="{{asset($product->getFirstMediaUrl('photo'))}}"/>
                                <input type="file" class="form-control  {{ $errors->has('photo')?' is-invalid':'' }}"
                                       name="photo" id="photo">
                                @if($errors->has('photo'))
                                    <div class='col-sm-12'><small class='text-danger'>
                                            @foreach($errors->get('photo') as $message)
                                            {{ $message }}</br>
                                            @endforeach
                                        </small></div>
                                @endif
                            </div>
                        </div>
                        <div class="row col-md-12">
                            <div class="col-md-12 text-center">
                                <button type="submit" class="btn btn-circle btn-primary">
                                    Сохранить
                                </button>
                                <a class="btn btn-circle btn-danger" href="{{ route('admin.products.index') }}">
                                    Отмена
                                </a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/admin/product/index.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')
@section('css')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/7.2.0/sweetalert2.min.css">
@stop


@section('content_header')
    <h1 class="m-0 text-dark">Products</h1>
@stop

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    @if (session('success'))
                        <div class="col-xs-12" style="padding-top: 20px;">
                            <div class="alert alert-success alert-dismissible">
                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                                <i class="icon fa fa-check"></i>
                                {{ session('success') }}
                            </div>
                        </div>
                @endif
                <!-- BEGIN Portlet PORTLET-->
                    <div class="portlet light" data-error-display="notific8">
                        <div class="portlet-title">
                            <div class="caption font-primary">
                            </div>
                            <div class="col-lg-9">
                                <a class="btn btn-sm btn-success" href="{{route('admin.products.create')}}">
                                    <i class="fa fa-plus"></i>Добавить
                                </a>
                            </div>
                        </div>

                        <div class="table-responsive">
                            <table class="table table-striped table-hover table-bordered" id="dataTable">
                                <thead>
                                <tr>
                                    <th>
                                        id
                                    </th>
                                    <th>
                                        Наименование
                                    </th>
                                    <th>
                                        SKU
                                    </th>
                                    <th>
                                        Цена
                                    </th>
                                    <th>
                                        Фотография
                                    </th>
                                    <th>
                                        Дата создание
                                    </th>
                                    <th>
                                        Дата обновление
                                    </th>
                                    <th>
                                        Действие
                                    </th>
                                </tr>
                                </thead>

                            </table>
                        </div>

                    </div>
                    <!-- END PORTLET-->
                </div>
            </div>
        </div>
    </div>
@stop
@section('js')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/7.2.0/sweetalert2.all.min.js"></script>
    <script src="{{ asset('vendor/datatables/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('vendor/datatables/js/dataTables.bootstrap4.min.js') }}"></script>
    <script>
        $('#dataTable').DataTable({
            processing: true,
            serverSide: true,
            ajax: window.location.href,
            columns: [
                {data: 'id', name: 'id'},
                {data: 'name', name: 'name'},
                {data: 'sku', name: 'sku'},
                {data: 'price', name: 'price'},
                {data: 'photo', name: 'photo'},
                {data: 'created_at', name: 'created_at'},
                {data: 'updated_at', name: 'updated_at'},
                {data: 'action', name: 'action'}
            ]
        });

        function Delete(id) {
            swal({
                title: "Вы точно хотите удалить?",
                text: "Выбранные вами данные будут удалены",
                type: "warning",
                buttons: true,
                dangerMode: true,
            }).then((willDelete) => {
                if (willDelete) {
                    $.ajax({
                        type: 'DELETE',
                        dataType: 'json',
                        url: window.location.href + '/' + id,
                        data: ({"_token": $('meta[name="csrf-token"]').attr('content')})
                    }).done(function (success) {
                        if (success) {
                            $('#dataTable').DataTable().ajax.reload();
                            swal({
                                title: "Успешно удален!",
                                type: "success",
                            });
                        }
                    })

                }
            });
        }
    </script>
@stop